version: '3.8'

services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: react-frontend
    restart: unless-stopped
    networks:
      - app-network

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: adonis-server
    restart: unless-stopped
    env_file: .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

    networks:
      - app-network

  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: unless-stopped
    env_file: .env
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: spleendb
      MYSQL_ROOT_PASSWORD: adonis
      MYSQL_USER: spleen
      MYSQL_PASSWORD: nmsiGSXJda3pk0d
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network
    depends_on:
      - frontend
      - backend

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
